steps:
  - name: gcr.io/cloud-builders/gsutil
    args: ["-m", "cp", "-r", "./vision/explore-api", "${_GS_URI}${BRANCH_NAME}/"]
  - name: gcr.io/cloud-builders/gsutil
    args: ["acl", "ch", "-r", "-u", "AllUsers:R", "${_GS_URI}${BRANCH_NAME}/"]

