steps:
  - name: gcr.io/cloud-builders/gsutil
    args: ["rb", "-f", "gs://cloud-build-${BRANCH_NAME}"]
  - name: gcr.io/cloud-builders/gsutil
    args: ["-m", "cp", "-r", "./vision/explore-api", "gs://cloud-build-${BRANCH_NAME}"]
  - name: gcr.io/cloud-builders/gsutil
    args: ["acl", "ch", "-r", "-u", "AllUsers:R", "gs://cloud-build-${BRANCH_NAME}"]

