steps:
  - name: gcr.io/cloud-builders/gsutil
    args: ["-m", "rm", "-r", "gs://${BRANCH_NAME}"]
  - name: gcr.io/cloud-builders/gsutil
    args: ["-m", "cp", "-r", "./vision/explore-api", "gs://${BRANCH_NAME}"]
  - name: gcr.io/cloud-builders/gsutil
    args: ["acl", "ch", "-r", "-u", "AllUsers:R", "gs://${BRANCH_NAME}"]

